### ISSUE TITLE
Browser Devlopment key ?

### ISSUE THREAD

**Issue by vj-1023** [Laimiux/RxTube#1]
@Laimiux 
hi , m new to development and my need to embed some YouTube videos in my application, i read your library and i think it's a great idea. but the init function asks for a browser_development_key , what's that about ? how do we get that ?

**Comment by Laimiux** [comment]
Go to https://console.developers.google.com/ and create a project. In that project, enable Youtube Data API. Then, go to "APIs & Auth -> Credentials",  create new api key, select browser key and in the form you can leave the http refferers empty.

Please close the issue if that works for you

**Comment by vj-1023** [comment]
Got it Sir !

Cheers,
  Vinit

**Comment by Krivoshey69** [comment]
Hi! I can not get the browser key. In https://console.developers.google.com/ everything changed. He is now in the mail come? Help me please.
