### ISSUE TITLE
Gradle error!

### ISSUE THREAD

**Issue by hatimmakki** [Laimiux/RxTube#11]
Hi,
I just put compile 'com.laimiux.rxtube:rxtube:0.0.2' into my project's gradle
but I got these Warnings and errors:
Warning 1:
Warning:WARNING: Dependency org.apache.httpcomponents:httpclient:4.0.1 is ignored for debug as it may be conflicting with the internal version provided by Android.
Warning 2:
Warning:WARNING: Dependency org.apache.httpcomponents:httpclient:4.0.1 is ignored for release as it may be conflicting with the internal version provided by Android.
Warning 3:
Warning:Conflict with dependency 'com.google.code.findbugs:jsr305'. Resolved versions for app (1.3.9) and test app (2.0.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Error:
Error:Execution failed for task ':app:prepareDebugAndroidTestDependencies'.
> Dependency Error. See console for details.

Any help?
thanks

**Comment by gencaysahinn** [comment]
Any result?

**Comment by Laimiux** [comment]
I'll look into this issue, this weekend.

**Comment by Laimiux** [comment]
Here is a fix
```
    compile('com.laimiux.rxtube:rxtube:0.0.3') {
        exclude group: 'com.google.code.findbugs', module: 'jsr305'
    }
```
