### ISSUE TITLE
Have you updated the gradle dependency link?

### ISSUE THREAD

**Issue by rajeevjaiswal** [Laimiux/RxTube#3]
App still crashes when playing the youtube video in lollipop device
Please let me know whether you have updated the gradle dependency link

**Comment by Laimiux** [comment]
I've updated gradle dependency to 1.3.0.  Does it still crash on clicking a video and going to the player?

**Comment by rajeevjaiswal** [comment]
Actually I was talking about 
compile('com.laimiux:android-youtube-listview:0.1.1@aar') {
    transitive = true;
}

Have you updated above ?
Because after importing your library via gradle  still in YouTube library api meta file I can see version 1.0 and not 1.2.2

**Comment by Laimiux** [comment]
I had to update maven repo. You can now use this instead:

``` java
compile('com.laimiux:android-youtube-listview:0.1.2@aar') {
    transitive = true;
}


```
