### ISSUE TITLE
Maven compile 'com.laimiux.rxtube:rxtube:0.0.1' not Working?

### ISSUE THREAD

**Issue by rajeevjaiswal** [Laimiux/RxTube#6]
I added it in gradle but when I try to call 
RxTube rxTube = new RxTube(youTube, browserKey);
        final String videoId = "iX-QaNzd-0Y";
        rxTube.create(new RxTube.Query<YouTube.Videos.List>() {
            @Override
            public YouTube.Videos.List create(YouTube youTube) throws Exception {
                final YouTube.Videos.List query = youTube.videos().list("snippet");
                query.setId(videoId);
                return query;

It is not able to resolve RxTube class
Even after manually adding import com.laimiux.rxyoutube.RxTube;
Still it is not able to resolve above import

**Comment by Laimiux** [comment]
Thanks for catching this! I need to fix the uploadArchives script because it is not including classes in the jar that it submits to the repo.

**Comment by Laimiux** [comment]
Okay, I've updated maven central repo with good jars.

Try 

``` groovy
compile 'com.laimiux.rxtube:rxtube:0.0.2'
```
